version: '3'
services:
  hbase:
    restart: always
    privileged: true
    image: harisekhon/hbase:1.3
    volumes:
      - /opt/docker/data/hbase/data:/hbase-data:rw
    ports:
      - "12181:2181"
      - "18080:8080"
      - "16010:16010"
  pinpoint:
    restart: always
    privileged: true
    image: zzjhacn/pinpoint
    depends_on:
      - hbase
    ports:
      - "28080:80"
      - "9994:9994"
      - "9995:9995"
      - "9996:9996"
